import{a as h,i as a,S as v}from"./assets/vendor-Qob_5Ba8.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&i(n)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();function m(t){return t.map(({webformatURL:o,largeImageURL:s,tags:i,likes:e,views:r,comments:n,downloads:w})=>`
        <li class="photo-card">
      <a href="${s}">
        <img src="${o}" alt="${i}" loading="lazy" />
      </a>

      <div class="info">
        <p><b>Likes</b> ${e}</p>
        <p><b>Views</b> ${r}</p>
        <p><b>Comments</b> ${n}</p>
        <p><b>Downloads</b> ${w}</p>
      </div>
        </li>
      `).join("")}const R="https://pixabay.com/api/",S="46866610-7fa4fac7b73adfddfb088af07",d=15;async function g(t,o=1){const s=new URLSearchParams({key:S,q:t,image_type:"photo",orientation:"horizontal",safesearch:"true",page:o,per_page:d});try{const i=await h.get(R,{params:s}),{hits:e,totalHits:r}=i.data;return e.length===0&&a.error({position:"topRight",title:"Error",message:"Sorry, no images matching your search query. Please try again!"}),{hits:e,totalHits:r}}catch(i){throw a.error({position:"topRight",title:"Error",message:"Error fetching images. Please try again!"}),i}}const p=document.querySelector(".search-form"),f=document.querySelector(".gallery"),y=document.querySelector(".loader"),u=document.querySelector(".load-more");h.defaults.timeout=5e3;p.addEventListener("submit",q);u.addEventListener("click",H);let b=new v(".gallery a",{captionsData:"alt",captionDelay:250}),l=1,L=0,c="";async function q(t){if(t.preventDefault(),f.innerHTML="",l=1,c=t.currentTarget.elements.query.value.trim(),!c){a.info({position:"topRight",title:"Info",message:"Please enter a search term."});return}E(),u.classList.add("load-more-hidden");try{const{hits:o,totalHits:s}=await g(c,l);L=s,o.length>0&&(f.innerHTML=m(o),b.refresh(),o.length===d&&u.classList.remove("load-more-hidden"))}catch{a.error({position:"topRight",title:"Error",message:"Error fetching images. Please try again!"})}finally{P(),p.reset()}}async function H(){l+=1,E();try{const{hits:t}=await g(c,l);t.length>0&&(f.insertAdjacentHTML("beforeend",m(t)),b.refresh(),(t.length<d||l*d>=L)&&(a.info({position:"topRight",title:"End of Results",message:"We're sorry, but you've reached the end of search results."}),u.classList.add("load-more-hidden")))}catch(t){console.error("Error loading more images:",t),a.error({position:"topRight",title:"Error",message:"Unable to load more images. Please try again later."})}finally{P(),M()}}function E(){y.classList.remove("hidden")}function P(){y.classList.add("hidden")}function M(){const t=f.firstElementChild;if(!t)return;const{height:o}=t.getBoundingClientRect();window.scrollBy({top:o*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
