import{a as E,i as c,S as P}from"./assets/vendor-Qob_5Ba8.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const s of r.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&a(s)}).observe(document,{childList:!0,subtree:!0});function i(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(e){if(e.ep)return;e.ep=!0;const r=i(e);fetch(e.href,r)}})();function m(t){return t.map(({webformatURL:o,largeImageURL:i,tags:a,likes:e,views:r,comments:s,downloads:b})=>`
        <li class="photo-card">
      <a href="${i}">
        <img src="${o}" alt="${a}" loading="lazy" />
      </a>

      <div class="info">
        <p><b>Likes</b> ${e}</p>
        <p><b>Views</b> ${r}</p>
        <p><b>Comments</b> ${s}</p>
        <p><b>Downloads</b> ${b}</p>
      </div>
        </li>
      `).join("")}const w="https://pixabay.com/api/",S="46866610-7fa4fac7b73adfddfb088af07",f=15;async function u(t,o=1){const i=new URLSearchParams({key:S,q:t,image_type:"photo",orientation:"horizontal",safesearch:"true",page:o,per_page:f});try{const a=await E.get(w,{params:i}),{hits:e,totalHits:r}=a.data;return e.length===0&&c.error({position:"topRight",title:"Error",message:"Sorry, no images matching your search query. Please try again!"}),{hits:e,totalHits:r}}catch(a){throw c.error({position:"topRight",title:"Error",message:"Error fetching images. Please try again!"}),a}}const h=document.querySelector(".search-form"),l=document.querySelector(".gallery"),g=document.querySelector(".loader"),d=document.querySelector(".load-more");h.addEventListener("submit",v);d.addEventListener("click",R);let p=new P(".gallery a",{captionsData:"alt",captionDelay:250}),n=1,q=0;async function v(t){t.preventDefault(),l.innerHTML="",n=1;const o=t.currentTarget.elements.query.value.trim();if(!o){c.info({position:"topRight",title:"Info",message:"Please enter a search term."});return}y(),d.classList.add("load-more-hidden");try{const{hits:i,totalHits:a}=await u(o,n);n===1&&(q=a),i.length>0&&(l.innerHTML=m(i),p.refresh(),i.length===f&&d.classList.remove("load-more-hidden"))}catch{c.error({position:"topRight",title:"Error",message:"Error fetching images. Please try again!"})}finally{L(),h.reset()}}async function R(){n+=1,y();try{const{hits:t}=await u(query,n);t.length>0&&(l.insertAdjacentHTML("beforeend",m(t)),p.refresh(),t.length<f&&d.classList.add("load-more-hidden"))}catch(t){console.error("Error loading more images:",t),c.error({position:"topRight",title:"Error",message:"Unable to load more images. Please try again later."})}finally{L(),H()}}function y(){g.classList.remove("hidden")}function L(){g.classList.add("hidden")}function H(){const{height:t}=l.firstElementChild.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
